### ISSUE TITLE
Problem with sign-in using x-ms-RefreshTokenCredential

### ISSUE THREAD

**Issue by pawp81** [leechristensen/RequestAADRefreshToken#1]
Are you sure the describe method works?
I tried clearing all cookies and creating only x-ms-RefreshTokenCredential with DATA field derived from the output of RequestAADRefreshToken.exe and then refreshed the website (I also tried entreing https://login.microsoftonline.com/login.srf) but I wasn't signed-in. Instead I was asked to enter the username

**Comment by leechristensen** [comment]
The capability still works, but Microsoft has changed how this works underneath. You'll need to reverse the Chrome extension to find out how to do it via the browser. Similarly, you could use [ROADTools ](https://twitter.com/_dirkjan/status/1312095317614047232) to do a similar thing.

**Comment by pawp81** [comment]
I tried with ROADtools generated x-ms-RefreshTokenCredential cookie injected to Chrome but also no luck. ROADTools allowed me to generate refresh and access tokens though that I successfully used for authentication on different device.
