### ISSUE TITLE
Run at victim?

### ISSUE THREAD

**Issue by tijldeneut** [leechristensen/RequestAADRefreshToken#2]
Hi, 
Just a question. 
This tool (or one of these tools) are meant to be run on the victim?

Would there be a possibility to extract the necessary data from the victim (via reg save or xcopy) and perform this on a non-AzureAD machine? 
I tried manually extracting the mentioned registry keys and importing them into a clean Win10, but the tool runs without DATA.

Thanks in advance, nice work!

**Comment by svrooij** [comment]
> non-AzureAD machine

Not possible, this technique especially used the SSO functionality with Azure AD to get tokens.

> run on the victim

I guess you could run this at the victim, extract the stdout (text output), parse it and send it to your computer. If you set the cookie on your local machine, you might get access as that user.
The project goal is to show that it's possible for other applications to get these tokens (without user interaction). If you want to use that for malicious activities that it up to you.

Sorry @leechristensen for trying to answer some questions.

**Comment by tijldeneut** [comment]
FYI: https://www.youtube.com/watch?v=yHKpF7QaKuc
(I'll close this for now, thank you very much for the reply)
